/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author aluno
 */
public class fPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fPrincipal
     */
    public fPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadCategoria = new javax.swing.JMenuItem();
        miCadCliente = new javax.swing.JMenuItem();
        miCadProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsCategoria = new javax.swing.JMenuItem();
        miConsCliente = new javax.swing.JMenuItem();
        miConsProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        miCadCategoria.setText("Categoria");
        jMenu1.add(miCadCategoria);

        miCadCliente.setText("Cliente");
        jMenu1.add(miCadCliente);

        miCadProduto.setText("Produto");
        jMenu1.add(miCadProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        miConsCategoria.setText("Categoria");
        jMenu2.add(miConsCategoria);

        miConsCliente.setText("Cliente");
        jMenu2.add(miConsCliente);

        miConsProduto.setText("Produto");
        jMenu2.add(miConsProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem miCadCategoria;
    public javax.swing.JMenuItem miCadCliente;
    public javax.swing.JMenuItem miCadProduto;
    public javax.swing.JMenuItem miConsCategoria;
    public javax.swing.JMenuItem miConsCliente;
    public javax.swing.JMenuItem miConsProduto;
    // End of variables declaration//GEN-END:variables
}
